### PR TITLE
update readme examples

### PR DESCRIPTION
**Pull request by murat-aka**

### CODE REVIEW

**Comment by zenorocha** [comment]
I don't get it, why are you adding links to your fork?

**Comment by murat-aka** [comment]
the examples will be like this. when you click. you ll see them live

tracking

**Comment by murat-aka** [comment]
check this out

https://github.com/murat-aka/tracking.js

**Comment by jeromeetienne** [comment]
This one seems good. 

modulo the typo in the url. it should point on tracking.js repository instead.

**Comment by murat-aka** [comment]
Ok guys thanks. I ll fix the typos.

**Comment by murat-aka** [comment]
travis ci fails. why?

shall I create a new fork and resubmit changes?

**Comment by murat-aka** [comment]
Hi, the Travis CI build fails

even after a fresh rebase.

**Comment by murat-aka** [comment]
in .travis.yml file
nodejs version was 0.11 
after changing it to 6.1
the Travis CI builds passed

**Comment by ghost** [comment]
Letting law monitor phone for potential hackers tracking

**Pull request closed without merging**
